BORN IN 1989
NATURAL BLONDE WITH NATURAL CURLS
HAS SHORT, STRAIGHT HAIR THESE DAYS; WORKS ON HER
IS 5'10.5" TALL
HAS RELEASED 5 OFFICIAL ALBUMS
IS ABSOLUTELY GORGEOUS IF YOU KNOW WHAT YOU'RE LOOKING FOR AND YOU'RE NOT AN IDIOT
IS LOVE
